import { GoogleGenAI } from '@google/genai';
const PRIMARY='gemini-3.5-flash',FALLBACK='gemini-3.1-flash-lite';
const KEY=process.env.GEMINI_API_KEY||process.env.GOOGLE_GENERATIVE_AI_API_KEY||'';
const hits=new Map();
const send=(res,status,data)=>{res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(data))};
function allow(req){const key=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'x').split(',')[0],now=Date.now(),a=(hits.get(key)||[]).filter(t=>now-t<600000);if(a.length>=5)return false;a.push(now);hits.set(key,a);return true}
function read(req){return new Promise((ok,no)=>{let s='',n=0;req.on('data',c=>{n+=c.length;if(n>262144){no(Error('Payload muito grande'));req.destroy()}else s+=c});req.on('end',()=>{try{ok(JSON.parse(s||'{}'))}catch{no(Error('JSON inválido'))}});req.on('error',no)})}
function normalize(items){const m=Math.max(...items.map(x=>x.fit)),w=items.map(x=>Math.exp((x.fit-m)/.12)),z=w.reduce((a,b)=>a+b,0);return items.map((x,i)=>({...x,probability:+(w[i]/z*100).toFixed(1)}))}
async function call(model,d){const candidates=d.candidates.slice(0,5),ids=candidates.map(x=>x.course),prompt=`Você é um assistente de Orientação Profissional e de Carreira, nunca um psicólogo. Não diagnostique nem emita laudo. Analise somente estes cursos: ${ids.join(' | ')}. Retorne JSON válido com overallConfidence (baixa, moderada ou alta), profileSummary, judgements (3 a 5 objetos com course, adjustment entre -0.10 e +0.10, rationale, evidence, counterevidence e experiment), missingInformation e ethicalNote. Fundamente apenas nos interesses RIASEC, valores, energia, limites e evidências presentes. Mostre contrapontos, lacunas e um microexperimento de baixo risco. Não invente salário, mercado, instituição, reconhecimento, duração ou empregabilidade. Percentuais são aderências relativas, não chances de sucesso. Dossiê anonimizado: ${JSON.stringify(d)}`;const ai=new GoogleGenAI({apiKey:KEY});const response=await ai.models.generateContent({model,contents:prompt,config:{temperature:.2,responseMimeType:'application/json'}});const out=response.text;if(!out)throw Error('Resposta estruturada ausente');return{data:JSON.parse(out),model,usage:response.usageMetadata}}
async function analyze(d){let last;for(const model of[PRIMARY,FALLBACK])try{return await call(model,d)}catch(e){last=e;if(![404,429,500,502,503,504].includes(e.status))break}throw last}
function finalize(d,x){const base=new Map(d.candidates.slice(0,5).map(v=>[v.course,v])),used=new Set(),rows=[];for(const q of x.judgements||[]){if(used.has(q.course)||!base.has(q.course))continue;used.add(q.course);const b=base.get(q.course),adj=Math.max(-.1,Math.min(.1,Number(q.adjustment)||0));rows.push({q,b,fit:Math.max(0,Math.min(1,Number(b.fit)+adj)),adj})}if(rows.length<3)throw Error('A IA não retornou três cursos válidos');const p=normalize(rows),width=x.overallConfidence==='alta'?8:x.overallConfidence==='moderada'?13:19;return{roleLabel:'Assistente de orientação profissional por IA',modelUsed:x.model,overallConfidence:x.overallConfidence,profileSummary:x.profileSummary,recommendations:p.map(v=>({course:v.q.course,probability:v.probability,interval:[Math.max(0,+(v.probability-width).toFixed(1)),Math.min(100,+(v.probability+width).toFixed(1))],baseFit:+Number(v.b.fit).toFixed(3),aiAdjustment:v.adj,rationale:v.q.rationale,evidence:v.q.evidence||[],counterevidence:v.q.counterevidence||[],experiment:v.q.experiment})),missingInformation:x.missingInformation||[],ethicalNote:x.ethicalNote||'Resultado exploratório, não diagnóstico, laudo ou decisão automática.',usage:x.usage}}
export default async function handler(req,res){if(req.method==='GET')return send(res,200,{ok:true,service:'doran-unified',primaryModel:PRIMARY,fallbackModel:FALLBACK,aiConfigured:Boolean(KEY)});if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});if(!KEY)return send(res,503,{error:'ai_not_configured',message:'A variável GEMINI_API_KEY ainda não foi configurada na Vercel.'});if(!allow(req))return send(res,429,{error:'rate_limited',message:'Limite temporário. Tente novamente em alguns minutos.'});try{const b=await read(req);if(b.consentToAI!==true)return send(res,400,{error:'consent_required',message:'É necessário consentimento explícito.'});let d=b.dossier;if(!d||!Array.isArray(d.candidates)||d.candidates.length<3)return send(res,400,{error:'invalid_dossier',message:'Dossiê inválido ou incompleto.'});d={...d,context:{...d.context,name:undefined,email:undefined,phone:undefined,address:undefined}};const x=await analyze(d);return send(res,200,finalize(d,x))}catch(e){return send(res,502,{error:'ai_failed',message:e.message})}}
